name: Build and publish nuget package(s)


on:
  release:
    # Workflows are not triggered for the created, edited, or deleted activity types for draft releases.
    types:
      - published

  workflow_dispatch:


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Dotnet info
      run: dotnet --info

    - uses: jannemattila/get-version-from-tag@v3
      id: get-version-from-tag

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release -p:Version=${{steps.get-version-from-tag.outputs.version}}

    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Pack
      run: dotnet pack --no-build --configuration Release


  publish-github:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      packages: write

    steps:
    - name: Publish to GitHub Packages
      run: dotnet nuget push "**/*.nupkg" --source "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json" --api-key "${{secrets.GITHUB_TOKEN}}" --skip-duplicate


  publish-nuget:
    name: Publish to NuGet Registry
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      packages: write

    steps:
    - name: Publish to NuGet Registry
      run: dotnet nuget push "**/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key "${{secrets.NUGET_API_KEY}}" --skip-duplicate
